sudo: required
language: haxe
haxe:
  - "3.4.7"
addons:
  apt:
    packages:
    - cmake
    - libbcel-java
    - openjdk-8-jdk
    - libgd-gd2-perl
    - nodejs
script: 
    - mkdir build
    - cd build 
    - cmake ..
    - make
    - make test
